iTasksProject/iTasksProject/Controllers/iTasksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using iTasksProject.Models;
using System.IO;

namespace iTasksProject.Controllers
{
    [Authorize]
    public class iTasksController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: iTasks
        public ActionResult Index()
        {
            var userId = User.Identity.GetUserId();
            var user = db.Users.Find(userId);
            var model = new iTaskViewModel();
            model.tasks = db.iTasks.Select(m => m).Where(m => m.User.Id == user.Id).OrderBy(m => m.Priority).ToList();
            model.task = new iTask();
            return View(model);
        }

        public ActionResult Edit(int? id)
        {
            iTask iTask = db.iTasks.Find(id);
            db.iTasks.Remove(iTask);
            db.SaveChanges();
            var userId = User.Identity.GetUserId();
            var user = db.Users.Find(userId);
            var model = new iTaskViewModel();
            model.tasks = db.iTasks.Select(m => m).Where(m => m.User.Id == user.Id).OrderBy(m => m.Priority).ToList();
            model.task = db.iTasks.Find(id);
            return View("Index", model);
        }


        // POST: iTasks/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(iTaskViewModel iTask)
        {
            var userId = User.Identity.GetUserId();
            var user = db.Users.Find(userId);
            var model = new iTaskViewModel();
            model.tasks = db.iTasks.Select(m => m).Where(m => m.User.Id == user.Id).OrderBy(m => m.Priority).ToList();
            model.task = null;
            if (ModelState.IsValid)
            {
                if (db.iTasks.Find(iTask.task.Id) != null)
                {
                    db.iTasks.Remove(iTask.task);
                }
                iTask.task.User = user;
                db.iTasks.Add(iTask.task);
                db.SaveChanges();
                return RedirectToAction("Index" , model );
            }
            model.task = iTask.task;
            return View("Index",model);
        }

        // GET: iTasks/Edit/5
        public ActionResult MarkComplete(int id)
        {
            if (ModelState.IsValid)
            {
                bool complete = db.iTasks.Find(id).Complete;
                db.iTasks.Find(id).Complete = !complete;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View("Index");
        }

        // GET: iTasks/Delete/5
        public ActionResult Delete(int? id)
        {
            iTask iTask = db.iTasks.Find(id);
            db.iTasks.Remove(iTask);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult ProfileImage()
        {
            var image = db.Users.Find(User.Identity.GetUserId()).ProfilePhoto;
            if (image != null)
            {
                return File(image, "image/jpg", "ProfilePhoto.jpg");
            }
            else
            {

                string path = Server.MapPath("..") + Url.Content("~/Content/iTasksTemplate") + "/img/default-profile.png";
                FileStream fs = new FileStream(path, FileMode.Open, FileAccess.Read);
                StreamReader sw = new StreamReader(fs);

                byte[] photo = new byte[fs.Length];
                fs.Read(photo, 0, (int)fs.Length);
                return File(photo, "image/jpg", "ProfilePhoto.png");
            }
        }

        // GET: Profile Image
        public ActionResult CoverImage()
        {
            var image = db.Users.Find(User.Identity.GetUserId()).CoverPhoto;
            if (image != null)
            {
                return File(image, "image/jpg", "CoverPhoto.jpg");
            }
            else
            {
                string path = Server.MapPath("..") + Url.Content("~/Content/iTasksTemplate") + "/img/default-cover.jpg";
                FileStream fs = new FileStream(path, FileMode.Open, FileAccess.Read);
                StreamReader sw = new StreamReader(fs);

                byte[] photo = new byte[fs.Length];
                fs.Read(photo, 0, (int)fs.Length);
                return File(photo, "image/jpg", "CoverPhoto.jpg");
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

iTasksProject/iTasksProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

iTasksProject/iTasksProject/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="@Url.Content("~/Content/iTasksTemplate/")css/bootstrap.min.css">
    <link rel="stylesheet" href="@Url.Content("~/Content/iTasksTemplate/")css/LoginStyle.css">
    <script src="@Url.Content("~/Content/iTasksTemplate/")js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
    <link rel='stylesheet prefetch' href='http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css'>

</head>
<body>
    @RenderBody()
    @RenderSection("scripts", required: true)
</body>
</html>

iTasksProject/iTasksProject/Views/Shared/_Message.cshtml
@using iTasksProject.Models
@using iTasksProject.Resources
@model ContactMessageModel

<hr style="margin-top:15px;" />
<div class="row">
    <div class="col-md-4 col-sm-5 col-xs-5" style="padding-left:10px;margin-top:10px;">
        <h5 style="margin:10px 0;">@Model.userName</h5>
        <h5 style="margin:10px 0;">@Model.userEmail</h5>
        <h5 style="margin:10px 0;">@Model.subject</h5>
    </div>
    <div class="col-md-6 col-sm-3 col-xs-3" style="text-align:left;border-left:solid 1px #e3e3e3;margin-top:15px;">
        @Model.message
    </div>
    <div class="col-md-2 col-sm-2 col-xs-3 pull-right" style="padding-top:50px;">
        @Html.ActionLink(@lang.Delete, "DeleteMessage", "Admin", new { id = Model.Id }, new { @class = "btn btn-default iTask-btn " })
    </div>
</div>

iTasksProject/iTasksProject/Views/Shared/_User.cshtml
@using iTasksProject.Models
@using iTasksProject.Resources
@model ApplicationUser
@{
    ViewBag.PhoneNumber = Model.PhoneNumber == null ? @lang.NoPhoneNum : Model.PhoneNumber;
}


<hr style="margin:0;" />
<div class="row">
    <div class="col-md-3 col-sm-3 col-xs-3" style="padding:10px;margin-left:15px;">
        <img class="img-responsive img-thumbnail" src='@Url.Action("userImage", new { Id = Model.Id })' style="width:100%;text-align:center;" alt="Profile Image" />
    </div>
    <div class="col-md-5 col-sm-5 col-xs-5" style="padding-left:0;margin-top:25px;">
        <h4 style="margin:10px 0;">@lang.Name : @Model.UserName</h4>
        <h4 style="margin:10px 0;">@lang.Email : @Model.Email</h4>
        <h4 style="margin:10px 0;">@lang.PhoneNumber : @ViewBag.PhoneNumber</h4>
    </div>
    <div class="col-md-3 col-sm-3 col-xs-3 pull-right" style="padding-top:50px;">
        @Html.ActionLink(@lang.DeleteUser, "DeleteUser", "Admin", new { id = Model.Id }, new { @class = "btn btn-default iTask-btn " })
        @Html.ActionLink(@lang.MakeAdmin, "AddRoleToUser", "Admin", new { id = Model.Id }, new { @class = "btn btn-default iTask-btn" })
    </div>
</div>

iTasksProject/iTasksProject/Views/Shared/_iTask.cshtml
@using iTasksProject.Models
@using iTasksProject.Resources
@model iTask
@{ 
    if (Model.Description != null)
    {
        ViewBag.Desc = Model.Description.Length > 35 ? String.Join( " " , Model.Description.Split(' ').Take(4).ToArray()) + "...." : Model.Description;
    }
    else
    {
        ViewBag.Desc = "";
    }
}


<hr style="margin:0;" />
<div class="row">
    <div class="col-md-2 col-sm-2 col-xs-2" style="margin-right:0;padding-right:0;">
        @Html.DisplayFor(m=>m.Priority)
    </div>
    <div class="col-md-6 col-sm-6 col-xs-6" style="margin-left:3px;padding-left:0;">
        <h3 style="margin:5px 0;">@Model.Name</h3>
        <p style="margin:0 10px;">@ViewBag.Desc </p>
    </div>
    <div class="col-md-3 col-sm-3 col-xs-3 pull-right">
        @if (Model.Complete)
        {
            @Html.ActionLink(@lang.Uncomplete , "MarkComplete", "iTasks", new { id = Model.Id }, new { @class = "btn btn-default iTask-btn" })
        }
        else
        {
            @Html.ActionLink(@lang.Uncomplete , "MarkComplete", "iTasks", new { id = Model.Id }, new { @class = "btn btn-default iTask-btn"});
        }
        @Html.ActionLink(@lang.Delete, "Delete", "iTasks", new { id = Model.Id }, new { @class = "btn btn-default iTask-btn " })
        @Html.ActionLink(@lang.Edit, "Edit", "iTasks", new { id = Model.Id }, new { @class = "btn btn-default iTask-btn"})
    </div>
</div>

iTasksProject/iTasksProject/Views/Shared/_iTasksLayout.cshtml
@using iTasksProject.Resources
<!DOCTYPE html>
<html>
<head>
    <title>@Page.Title</title>
    <link rel="stylesheet" href="@Url.Content("~/Content/iTasksTemplate/")css/owl.carousel.css">
    <link rel="stylesheet" href="@Url.Content("~/Content/iTasksTemplate/")css/bootstrap.min.css">
    <link rel="stylesheet" href="@Url.Content("~/Content/iTasksTemplate/")css/font-awesome.min.css">
    <link rel="stylesheet" href="@Url.Content("~/Content/iTasksTemplate/")css/style.css">
    <link rel="stylesheet" href="@Url.Content("~/Content/iTasksTemplate/")css/ionicons.min.css">
    <link rel="stylesheet" href="@Url.Content("~/Content/iTasksTemplate/")css/animate.css">
    <link rel="stylesheet" href="@Url.Content("~/Content/iTasksTemplate/")css/responsive.css">


    <script src="@Url.Content("~/Content/iTasksTemplate/")js/vendor/modernizr-2.6.2.min.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="js/vendor/jquery-1.10.2.min.js"><\/script>')</script>
    <script src="@Url.Content("~/Content/iTasksTemplate/")js/bootstrap.min.js"></script>
    <script src="@Url.Content("~/Content/iTasksTemplate/")js/owl.carousel.min.js"></script>
    <script src="@Url.Content("~/Content/iTasksTemplate/")js/plugins.js"></script>
    <script src="@Url.Content("~/Content/iTasksTemplate/")js/min/waypoints.min.js"></script>
    <script src="@Url.Content("~/Content/iTasksTemplate/")js/jquery.counterup.js"></script>
    <script src="@Url.Content("~/Content/iTasksTemplate/")js/main.js"></script>
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <header>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <nav class="navbar navbar-default navbar-static-top">
                        <div class="container-fluid">
                            <div class="navbar-header">
                                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                                    <span class="sr-only">Toggle navigation</span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                </button>
                                <a class="navbar-brand" href="@Url.Action("Index","Home")">
                                    <img height="44" src="@Url.Content("~/Content/iTasksTemplate/")img/iTasksLogo001.png" alt="Logo">
                                </a>
                            </div>
                            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                                <ul class="nav navbar-nav navbar-right">
                                    <li>@Html.ActionLink(@lang.Home, "Index", "Home")</li>
                                    <li>@Html.ActionLink(@lang.Contact, "Contact", "Home")</li>
                                    @Html.Partial("_LoginPartial")
                                    <li>
                                        @Html.ActionLink("En ", "ChangeCulture", "Home", new { lang = "en", returnurl = this.Request.RawUrl }, new { @style = "padding-right:3px;" })
                                    </li>                                                                                                      
                                    <li>                                                                                                       
                                        @Html.ActionLink("| Tr", "ChangeCulture", "Home", new { lang = "tr", returnUrl = this.Request.RawUrl }, new { @style = "padding-left:3px;" } )
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </nav>
                </div>
            </div>
        </div>
    </header>

    <div class="body">@RenderBody()</div>

    <footer>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <p>Copyright &copy; Designed by @Html.ActionLink("iTasks.com", "Index", "Home")</p>
                </div>
            </div>
        </div>
    </footer>
    @RenderSection("scripts", required: false)
</body>
</html>